# Generated by Django 3.0 on 2020-01-31 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0002_login_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reg_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=15)),
                ('login_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examapp.Login')),
            ],
        ),
    ]
